name: qr_code_scanner_example
description: Demonstrates how to use the flutter_qr plugin.
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

  qr_code_scanner:
    path: ../


flutter:
  uses-material-design: true
